# Start system info bar
pwsh /home/nixos/.sysinfo.ps1 &

# Automatic screen dimmer
pwsh /home/nixos/.brightness_controller.ps1 &

# Custom mappings
setxkbmap -layout us
xkbcomp /home/nixos/remaps.xkb $DISPLAY

# Start DWM
exec dwm
