# Start audio controller
sh systemd --user &
sh $env:XDG_RUNTIME_DIR="/run/user/$(id -u)"
sh feh --bg-fill '/home/nixos/Pictures/Photoshop Work/the-desktop.jpg'
# sh xwinwrap -fs -fdt -b -nf -- mpv --no-border --loop --vo=x11 --wid=%WID /home/nixos/Downloads/live-bridge.mp4 &

# System info for top bar
pwsh /home/nixos/.sysinfo.ps1 &

# Automatic screen dimmer
pwsh /home/nixos/.brightness_controller.ps1 &

# Start DWM
exec dwm
