# System info for top bar
pwsh /home/nixos/.sysinfo.ps1 &

# Automatic screen dimmer
pwsh /home/nixos/.brightness_controller.ps1 &

# Powershell user checker
#sudo rm /tmp/sdf
#xsetroot -name 'deleted'

# Start DWM
exec dwm
